blank_issues_enabled: false
issue_templates:
  - name: "ğŸ”¥ Feature"
    description: "ì´ìŠˆë¥¼ ìƒì„±í•˜ë©°, ìƒì„±ëœ ì´ìŠˆëŠ” Jiraì™€ ì—°ë™ë©ë‹ˆë‹¤."
    title: "Feat: "
    labels: ["âœ¨ Feat"]
    file: ".github/ISSUE_TEMPLATE/issue-form.yml"
  
  - name: "ğŸ Bug"
    description: "ë²„ê·¸ ì´ìŠˆë¥¼ ìƒì„±í•˜ë©°, ìƒì„±ëœ ì´ìŠˆëŠ” Jiraì™€ ì—°ë™ë©ë‹ˆë‹¤."
    title: "Bug: "
    labels: ["ğŸ Bug"]
    file: ".github/ISSUE_TEMPLATE/bug-form.yml"